-- AlterTable
ALTER TABLE "Employees" ADD COLUMN     "endWork" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "handphone" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "officeEmail" TEXT DEFAULT E'',
ADD COLUMN     "officeEmailPassword" TEXT DEFAULT E'',
ADD COLUMN     "startWork" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" TEXT DEFAULT E'active';
